// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace NISTMLTestML.Model
{
    public class ModelInput
    {
        [ColumnName("Number"), LoadColumn(0)]
        public float Number { get; set; }


        [ColumnName("d1"), LoadColumn(1)]
        public float D1 { get; set; }


        [ColumnName("d2"), LoadColumn(2)]
        public float D2 { get; set; }


        [ColumnName("d3"), LoadColumn(3)]
        public float D3 { get; set; }


        [ColumnName("d4"), LoadColumn(4)]
        public float D4 { get; set; }


        [ColumnName("d5"), LoadColumn(5)]
        public float D5 { get; set; }


        [ColumnName("d6"), LoadColumn(6)]
        public float D6 { get; set; }


        [ColumnName("d7"), LoadColumn(7)]
        public float D7 { get; set; }


        [ColumnName("d8"), LoadColumn(8)]
        public float D8 { get; set; }


        [ColumnName("d9"), LoadColumn(9)]
        public float D9 { get; set; }


        [ColumnName("d10"), LoadColumn(10)]
        public float D10 { get; set; }


        [ColumnName("d11"), LoadColumn(11)]
        public float D11 { get; set; }


        [ColumnName("d12"), LoadColumn(12)]
        public float D12 { get; set; }


        [ColumnName("d13"), LoadColumn(13)]
        public float D13 { get; set; }


        [ColumnName("d14"), LoadColumn(14)]
        public float D14 { get; set; }


        [ColumnName("d15"), LoadColumn(15)]
        public float D15 { get; set; }


        [ColumnName("d16"), LoadColumn(16)]
        public float D16 { get; set; }


        [ColumnName("d17"), LoadColumn(17)]
        public float D17 { get; set; }


        [ColumnName("d18"), LoadColumn(18)]
        public float D18 { get; set; }


        [ColumnName("d19"), LoadColumn(19)]
        public float D19 { get; set; }


        [ColumnName("d20"), LoadColumn(20)]
        public float D20 { get; set; }


        [ColumnName("d21"), LoadColumn(21)]
        public float D21 { get; set; }


        [ColumnName("d22"), LoadColumn(22)]
        public float D22 { get; set; }


        [ColumnName("d23"), LoadColumn(23)]
        public float D23 { get; set; }


        [ColumnName("d24"), LoadColumn(24)]
        public float D24 { get; set; }


        [ColumnName("d25"), LoadColumn(25)]
        public float D25 { get; set; }


        [ColumnName("d26"), LoadColumn(26)]
        public float D26 { get; set; }


        [ColumnName("d27"), LoadColumn(27)]
        public float D27 { get; set; }


        [ColumnName("d28"), LoadColumn(28)]
        public float D28 { get; set; }


        [ColumnName("d29"), LoadColumn(29)]
        public float D29 { get; set; }


        [ColumnName("d30"), LoadColumn(30)]
        public float D30 { get; set; }


        [ColumnName("d31"), LoadColumn(31)]
        public float D31 { get; set; }


        [ColumnName("d32"), LoadColumn(32)]
        public float D32 { get; set; }


        [ColumnName("d33"), LoadColumn(33)]
        public float D33 { get; set; }


        [ColumnName("d34"), LoadColumn(34)]
        public float D34 { get; set; }


        [ColumnName("d35"), LoadColumn(35)]
        public float D35 { get; set; }


        [ColumnName("d36"), LoadColumn(36)]
        public float D36 { get; set; }


        [ColumnName("d37"), LoadColumn(37)]
        public float D37 { get; set; }


        [ColumnName("d38"), LoadColumn(38)]
        public float D38 { get; set; }


        [ColumnName("d39"), LoadColumn(39)]
        public float D39 { get; set; }


        [ColumnName("d40"), LoadColumn(40)]
        public float D40 { get; set; }


        [ColumnName("d41"), LoadColumn(41)]
        public float D41 { get; set; }


        [ColumnName("d42"), LoadColumn(42)]
        public float D42 { get; set; }


        [ColumnName("d43"), LoadColumn(43)]
        public float D43 { get; set; }


        [ColumnName("d44"), LoadColumn(44)]
        public float D44 { get; set; }


        [ColumnName("d45"), LoadColumn(45)]
        public float D45 { get; set; }


        [ColumnName("d46"), LoadColumn(46)]
        public float D46 { get; set; }


        [ColumnName("d47"), LoadColumn(47)]
        public float D47 { get; set; }


        [ColumnName("d48"), LoadColumn(48)]
        public float D48 { get; set; }


        [ColumnName("d49"), LoadColumn(49)]
        public float D49 { get; set; }


        [ColumnName("d50"), LoadColumn(50)]
        public float D50 { get; set; }


        [ColumnName("d51"), LoadColumn(51)]
        public float D51 { get; set; }


        [ColumnName("d52"), LoadColumn(52)]
        public float D52 { get; set; }


        [ColumnName("d53"), LoadColumn(53)]
        public float D53 { get; set; }


        [ColumnName("d54"), LoadColumn(54)]
        public float D54 { get; set; }


        [ColumnName("d55"), LoadColumn(55)]
        public float D55 { get; set; }


        [ColumnName("d56"), LoadColumn(56)]
        public float D56 { get; set; }


        [ColumnName("d57"), LoadColumn(57)]
        public float D57 { get; set; }


        [ColumnName("d58"), LoadColumn(58)]
        public float D58 { get; set; }


        [ColumnName("d59"), LoadColumn(59)]
        public float D59 { get; set; }


        [ColumnName("d60"), LoadColumn(60)]
        public float D60 { get; set; }


        [ColumnName("d61"), LoadColumn(61)]
        public float D61 { get; set; }


        [ColumnName("d62"), LoadColumn(62)]
        public float D62 { get; set; }


        [ColumnName("d63"), LoadColumn(63)]
        public float D63 { get; set; }


        [ColumnName("d64"), LoadColumn(64)]
        public float D64 { get; set; }


        [ColumnName("d65"), LoadColumn(65)]
        public float D65 { get; set; }


        [ColumnName("d66"), LoadColumn(66)]
        public float D66 { get; set; }


        [ColumnName("d67"), LoadColumn(67)]
        public float D67 { get; set; }


        [ColumnName("d68"), LoadColumn(68)]
        public float D68 { get; set; }


        [ColumnName("d69"), LoadColumn(69)]
        public float D69 { get; set; }


        [ColumnName("d70"), LoadColumn(70)]
        public float D70 { get; set; }


        [ColumnName("d71"), LoadColumn(71)]
        public float D71 { get; set; }


        [ColumnName("d72"), LoadColumn(72)]
        public float D72 { get; set; }


        [ColumnName("d73"), LoadColumn(73)]
        public float D73 { get; set; }


        [ColumnName("d74"), LoadColumn(74)]
        public float D74 { get; set; }


        [ColumnName("d75"), LoadColumn(75)]
        public float D75 { get; set; }


        [ColumnName("d76"), LoadColumn(76)]
        public float D76 { get; set; }


        [ColumnName("d77"), LoadColumn(77)]
        public float D77 { get; set; }


        [ColumnName("d78"), LoadColumn(78)]
        public float D78 { get; set; }


        [ColumnName("d79"), LoadColumn(79)]
        public float D79 { get; set; }


        [ColumnName("d80"), LoadColumn(80)]
        public float D80 { get; set; }


        [ColumnName("d81"), LoadColumn(81)]
        public float D81 { get; set; }


        [ColumnName("d82"), LoadColumn(82)]
        public float D82 { get; set; }


        [ColumnName("d83"), LoadColumn(83)]
        public float D83 { get; set; }


        [ColumnName("d84"), LoadColumn(84)]
        public float D84 { get; set; }


        [ColumnName("d85"), LoadColumn(85)]
        public float D85 { get; set; }


        [ColumnName("d86"), LoadColumn(86)]
        public float D86 { get; set; }


        [ColumnName("d87"), LoadColumn(87)]
        public float D87 { get; set; }


        [ColumnName("d88"), LoadColumn(88)]
        public float D88 { get; set; }


        [ColumnName("d89"), LoadColumn(89)]
        public float D89 { get; set; }


        [ColumnName("d90"), LoadColumn(90)]
        public float D90 { get; set; }


        [ColumnName("d91"), LoadColumn(91)]
        public float D91 { get; set; }


        [ColumnName("d92"), LoadColumn(92)]
        public float D92 { get; set; }


        [ColumnName("d93"), LoadColumn(93)]
        public float D93 { get; set; }


        [ColumnName("d94"), LoadColumn(94)]
        public float D94 { get; set; }


        [ColumnName("d95"), LoadColumn(95)]
        public float D95 { get; set; }


        [ColumnName("d96"), LoadColumn(96)]
        public float D96 { get; set; }


        [ColumnName("d97"), LoadColumn(97)]
        public float D97 { get; set; }


        [ColumnName("d98"), LoadColumn(98)]
        public float D98 { get; set; }


        [ColumnName("d99"), LoadColumn(99)]
        public float D99 { get; set; }


        [ColumnName("d100"), LoadColumn(100)]
        public float D100 { get; set; }


        [ColumnName("d101"), LoadColumn(101)]
        public float D101 { get; set; }


        [ColumnName("d102"), LoadColumn(102)]
        public float D102 { get; set; }


        [ColumnName("d103"), LoadColumn(103)]
        public float D103 { get; set; }


        [ColumnName("d104"), LoadColumn(104)]
        public float D104 { get; set; }


        [ColumnName("d105"), LoadColumn(105)]
        public float D105 { get; set; }


        [ColumnName("d106"), LoadColumn(106)]
        public float D106 { get; set; }


        [ColumnName("d107"), LoadColumn(107)]
        public float D107 { get; set; }


        [ColumnName("d108"), LoadColumn(108)]
        public float D108 { get; set; }


        [ColumnName("d109"), LoadColumn(109)]
        public float D109 { get; set; }


        [ColumnName("d110"), LoadColumn(110)]
        public float D110 { get; set; }


        [ColumnName("d111"), LoadColumn(111)]
        public float D111 { get; set; }


        [ColumnName("d112"), LoadColumn(112)]
        public float D112 { get; set; }


        [ColumnName("d113"), LoadColumn(113)]
        public float D113 { get; set; }


        [ColumnName("d114"), LoadColumn(114)]
        public float D114 { get; set; }


        [ColumnName("d115"), LoadColumn(115)]
        public float D115 { get; set; }


        [ColumnName("d116"), LoadColumn(116)]
        public float D116 { get; set; }


        [ColumnName("d117"), LoadColumn(117)]
        public float D117 { get; set; }


        [ColumnName("d118"), LoadColumn(118)]
        public float D118 { get; set; }


        [ColumnName("d119"), LoadColumn(119)]
        public float D119 { get; set; }


        [ColumnName("d120"), LoadColumn(120)]
        public float D120 { get; set; }


        [ColumnName("d121"), LoadColumn(121)]
        public float D121 { get; set; }


        [ColumnName("d122"), LoadColumn(122)]
        public float D122 { get; set; }


        [ColumnName("d123"), LoadColumn(123)]
        public float D123 { get; set; }


        [ColumnName("d124"), LoadColumn(124)]
        public float D124 { get; set; }


        [ColumnName("d125"), LoadColumn(125)]
        public float D125 { get; set; }


        [ColumnName("d126"), LoadColumn(126)]
        public float D126 { get; set; }


        [ColumnName("d127"), LoadColumn(127)]
        public float D127 { get; set; }


        [ColumnName("d128"), LoadColumn(128)]
        public float D128 { get; set; }


        [ColumnName("d129"), LoadColumn(129)]
        public float D129 { get; set; }


        [ColumnName("d130"), LoadColumn(130)]
        public float D130 { get; set; }


        [ColumnName("d131"), LoadColumn(131)]
        public float D131 { get; set; }


        [ColumnName("d132"), LoadColumn(132)]
        public float D132 { get; set; }


        [ColumnName("d133"), LoadColumn(133)]
        public float D133 { get; set; }


        [ColumnName("d134"), LoadColumn(134)]
        public float D134 { get; set; }


        [ColumnName("d135"), LoadColumn(135)]
        public float D135 { get; set; }


        [ColumnName("d136"), LoadColumn(136)]
        public float D136 { get; set; }


        [ColumnName("d137"), LoadColumn(137)]
        public float D137 { get; set; }


        [ColumnName("d138"), LoadColumn(138)]
        public float D138 { get; set; }


        [ColumnName("d139"), LoadColumn(139)]
        public float D139 { get; set; }


        [ColumnName("d140"), LoadColumn(140)]
        public float D140 { get; set; }


        [ColumnName("d141"), LoadColumn(141)]
        public float D141 { get; set; }


        [ColumnName("d142"), LoadColumn(142)]
        public float D142 { get; set; }


        [ColumnName("d143"), LoadColumn(143)]
        public float D143 { get; set; }


        [ColumnName("d144"), LoadColumn(144)]
        public float D144 { get; set; }


        [ColumnName("d145"), LoadColumn(145)]
        public float D145 { get; set; }


        [ColumnName("d146"), LoadColumn(146)]
        public float D146 { get; set; }


        [ColumnName("d147"), LoadColumn(147)]
        public float D147 { get; set; }


        [ColumnName("d148"), LoadColumn(148)]
        public float D148 { get; set; }


        [ColumnName("d149"), LoadColumn(149)]
        public float D149 { get; set; }


        [ColumnName("d150"), LoadColumn(150)]
        public float D150 { get; set; }


        [ColumnName("d151"), LoadColumn(151)]
        public float D151 { get; set; }


        [ColumnName("d152"), LoadColumn(152)]
        public float D152 { get; set; }


        [ColumnName("d153"), LoadColumn(153)]
        public float D153 { get; set; }


        [ColumnName("d154"), LoadColumn(154)]
        public float D154 { get; set; }


        [ColumnName("d155"), LoadColumn(155)]
        public float D155 { get; set; }


        [ColumnName("d156"), LoadColumn(156)]
        public float D156 { get; set; }


        [ColumnName("d157"), LoadColumn(157)]
        public float D157 { get; set; }


        [ColumnName("d158"), LoadColumn(158)]
        public float D158 { get; set; }


        [ColumnName("d159"), LoadColumn(159)]
        public float D159 { get; set; }


        [ColumnName("d160"), LoadColumn(160)]
        public float D160 { get; set; }


        [ColumnName("d161"), LoadColumn(161)]
        public float D161 { get; set; }


        [ColumnName("d162"), LoadColumn(162)]
        public float D162 { get; set; }


        [ColumnName("d163"), LoadColumn(163)]
        public float D163 { get; set; }


        [ColumnName("d164"), LoadColumn(164)]
        public float D164 { get; set; }


        [ColumnName("d165"), LoadColumn(165)]
        public float D165 { get; set; }


        [ColumnName("d166"), LoadColumn(166)]
        public float D166 { get; set; }


        [ColumnName("d167"), LoadColumn(167)]
        public float D167 { get; set; }


        [ColumnName("d168"), LoadColumn(168)]
        public float D168 { get; set; }


        [ColumnName("d169"), LoadColumn(169)]
        public float D169 { get; set; }


        [ColumnName("d170"), LoadColumn(170)]
        public float D170 { get; set; }


        [ColumnName("d171"), LoadColumn(171)]
        public float D171 { get; set; }


        [ColumnName("d172"), LoadColumn(172)]
        public float D172 { get; set; }


        [ColumnName("d173"), LoadColumn(173)]
        public float D173 { get; set; }


        [ColumnName("d174"), LoadColumn(174)]
        public float D174 { get; set; }


        [ColumnName("d175"), LoadColumn(175)]
        public float D175 { get; set; }


        [ColumnName("d176"), LoadColumn(176)]
        public float D176 { get; set; }


        [ColumnName("d177"), LoadColumn(177)]
        public float D177 { get; set; }


        [ColumnName("d178"), LoadColumn(178)]
        public float D178 { get; set; }


        [ColumnName("d179"), LoadColumn(179)]
        public float D179 { get; set; }


        [ColumnName("d180"), LoadColumn(180)]
        public float D180 { get; set; }


        [ColumnName("d181"), LoadColumn(181)]
        public float D181 { get; set; }


        [ColumnName("d182"), LoadColumn(182)]
        public float D182 { get; set; }


        [ColumnName("d183"), LoadColumn(183)]
        public float D183 { get; set; }


        [ColumnName("d184"), LoadColumn(184)]
        public float D184 { get; set; }


        [ColumnName("d185"), LoadColumn(185)]
        public float D185 { get; set; }


        [ColumnName("d186"), LoadColumn(186)]
        public float D186 { get; set; }


        [ColumnName("d187"), LoadColumn(187)]
        public float D187 { get; set; }


        [ColumnName("d188"), LoadColumn(188)]
        public float D188 { get; set; }


        [ColumnName("d189"), LoadColumn(189)]
        public float D189 { get; set; }


        [ColumnName("d190"), LoadColumn(190)]
        public float D190 { get; set; }


        [ColumnName("d191"), LoadColumn(191)]
        public float D191 { get; set; }


        [ColumnName("d192"), LoadColumn(192)]
        public float D192 { get; set; }


        [ColumnName("d193"), LoadColumn(193)]
        public float D193 { get; set; }


        [ColumnName("d194"), LoadColumn(194)]
        public float D194 { get; set; }


        [ColumnName("d195"), LoadColumn(195)]
        public float D195 { get; set; }


        [ColumnName("d196"), LoadColumn(196)]
        public float D196 { get; set; }


        [ColumnName("d197"), LoadColumn(197)]
        public float D197 { get; set; }


        [ColumnName("d198"), LoadColumn(198)]
        public float D198 { get; set; }


        [ColumnName("d199"), LoadColumn(199)]
        public float D199 { get; set; }


        [ColumnName("d200"), LoadColumn(200)]
        public float D200 { get; set; }


        [ColumnName("d201"), LoadColumn(201)]
        public float D201 { get; set; }


        [ColumnName("d202"), LoadColumn(202)]
        public float D202 { get; set; }


        [ColumnName("d203"), LoadColumn(203)]
        public float D203 { get; set; }


        [ColumnName("d204"), LoadColumn(204)]
        public float D204 { get; set; }


        [ColumnName("d205"), LoadColumn(205)]
        public float D205 { get; set; }


        [ColumnName("d206"), LoadColumn(206)]
        public float D206 { get; set; }


        [ColumnName("d207"), LoadColumn(207)]
        public float D207 { get; set; }


        [ColumnName("d208"), LoadColumn(208)]
        public float D208 { get; set; }


        [ColumnName("d209"), LoadColumn(209)]
        public float D209 { get; set; }


        [ColumnName("d210"), LoadColumn(210)]
        public float D210 { get; set; }


        [ColumnName("d211"), LoadColumn(211)]
        public float D211 { get; set; }


        [ColumnName("d212"), LoadColumn(212)]
        public float D212 { get; set; }


        [ColumnName("d213"), LoadColumn(213)]
        public float D213 { get; set; }


        [ColumnName("d214"), LoadColumn(214)]
        public float D214 { get; set; }


        [ColumnName("d215"), LoadColumn(215)]
        public float D215 { get; set; }


        [ColumnName("d216"), LoadColumn(216)]
        public float D216 { get; set; }


        [ColumnName("d217"), LoadColumn(217)]
        public float D217 { get; set; }


        [ColumnName("d218"), LoadColumn(218)]
        public float D218 { get; set; }


        [ColumnName("d219"), LoadColumn(219)]
        public float D219 { get; set; }


        [ColumnName("d220"), LoadColumn(220)]
        public float D220 { get; set; }


        [ColumnName("d221"), LoadColumn(221)]
        public float D221 { get; set; }


        [ColumnName("d222"), LoadColumn(222)]
        public float D222 { get; set; }


        [ColumnName("d223"), LoadColumn(223)]
        public float D223 { get; set; }


        [ColumnName("d224"), LoadColumn(224)]
        public float D224 { get; set; }


        [ColumnName("d225"), LoadColumn(225)]
        public float D225 { get; set; }


        [ColumnName("d226"), LoadColumn(226)]
        public float D226 { get; set; }


        [ColumnName("d227"), LoadColumn(227)]
        public float D227 { get; set; }


        [ColumnName("d228"), LoadColumn(228)]
        public float D228 { get; set; }


        [ColumnName("d229"), LoadColumn(229)]
        public float D229 { get; set; }


        [ColumnName("d230"), LoadColumn(230)]
        public float D230 { get; set; }


        [ColumnName("d231"), LoadColumn(231)]
        public float D231 { get; set; }


        [ColumnName("d232"), LoadColumn(232)]
        public float D232 { get; set; }


        [ColumnName("d233"), LoadColumn(233)]
        public float D233 { get; set; }


        [ColumnName("d234"), LoadColumn(234)]
        public float D234 { get; set; }


        [ColumnName("d235"), LoadColumn(235)]
        public float D235 { get; set; }


        [ColumnName("d236"), LoadColumn(236)]
        public float D236 { get; set; }


        [ColumnName("d237"), LoadColumn(237)]
        public float D237 { get; set; }


        [ColumnName("d238"), LoadColumn(238)]
        public float D238 { get; set; }


        [ColumnName("d239"), LoadColumn(239)]
        public float D239 { get; set; }


        [ColumnName("d240"), LoadColumn(240)]
        public float D240 { get; set; }


        [ColumnName("d241"), LoadColumn(241)]
        public float D241 { get; set; }


        [ColumnName("d242"), LoadColumn(242)]
        public float D242 { get; set; }


        [ColumnName("d243"), LoadColumn(243)]
        public float D243 { get; set; }


        [ColumnName("d244"), LoadColumn(244)]
        public float D244 { get; set; }


        [ColumnName("d245"), LoadColumn(245)]
        public float D245 { get; set; }


        [ColumnName("d246"), LoadColumn(246)]
        public float D246 { get; set; }


        [ColumnName("d247"), LoadColumn(247)]
        public float D247 { get; set; }


        [ColumnName("d248"), LoadColumn(248)]
        public float D248 { get; set; }


        [ColumnName("d249"), LoadColumn(249)]
        public float D249 { get; set; }


        [ColumnName("d250"), LoadColumn(250)]
        public float D250 { get; set; }


        [ColumnName("d251"), LoadColumn(251)]
        public float D251 { get; set; }


        [ColumnName("d252"), LoadColumn(252)]
        public float D252 { get; set; }


        [ColumnName("d253"), LoadColumn(253)]
        public float D253 { get; set; }


        [ColumnName("d254"), LoadColumn(254)]
        public float D254 { get; set; }


        [ColumnName("d255"), LoadColumn(255)]
        public float D255 { get; set; }


        [ColumnName("d256"), LoadColumn(256)]
        public float D256 { get; set; }


        [ColumnName("d257"), LoadColumn(257)]
        public float D257 { get; set; }


        [ColumnName("d258"), LoadColumn(258)]
        public float D258 { get; set; }


        [ColumnName("d259"), LoadColumn(259)]
        public float D259 { get; set; }


        [ColumnName("d260"), LoadColumn(260)]
        public float D260 { get; set; }


        [ColumnName("d261"), LoadColumn(261)]
        public float D261 { get; set; }


        [ColumnName("d262"), LoadColumn(262)]
        public float D262 { get; set; }


        [ColumnName("d263"), LoadColumn(263)]
        public float D263 { get; set; }


        [ColumnName("d264"), LoadColumn(264)]
        public float D264 { get; set; }


        [ColumnName("d265"), LoadColumn(265)]
        public float D265 { get; set; }


        [ColumnName("d266"), LoadColumn(266)]
        public float D266 { get; set; }


        [ColumnName("d267"), LoadColumn(267)]
        public float D267 { get; set; }


        [ColumnName("d268"), LoadColumn(268)]
        public float D268 { get; set; }


        [ColumnName("d269"), LoadColumn(269)]
        public float D269 { get; set; }


        [ColumnName("d270"), LoadColumn(270)]
        public float D270 { get; set; }


        [ColumnName("d271"), LoadColumn(271)]
        public float D271 { get; set; }


        [ColumnName("d272"), LoadColumn(272)]
        public float D272 { get; set; }


        [ColumnName("d273"), LoadColumn(273)]
        public float D273 { get; set; }


        [ColumnName("d274"), LoadColumn(274)]
        public float D274 { get; set; }


        [ColumnName("d275"), LoadColumn(275)]
        public float D275 { get; set; }


        [ColumnName("d276"), LoadColumn(276)]
        public float D276 { get; set; }


        [ColumnName("d277"), LoadColumn(277)]
        public float D277 { get; set; }


        [ColumnName("d278"), LoadColumn(278)]
        public float D278 { get; set; }


        [ColumnName("d279"), LoadColumn(279)]
        public float D279 { get; set; }


        [ColumnName("d280"), LoadColumn(280)]
        public float D280 { get; set; }


        [ColumnName("d281"), LoadColumn(281)]
        public float D281 { get; set; }


        [ColumnName("d282"), LoadColumn(282)]
        public float D282 { get; set; }


        [ColumnName("d283"), LoadColumn(283)]
        public float D283 { get; set; }


        [ColumnName("d284"), LoadColumn(284)]
        public float D284 { get; set; }


        [ColumnName("d285"), LoadColumn(285)]
        public float D285 { get; set; }


        [ColumnName("d286"), LoadColumn(286)]
        public float D286 { get; set; }


        [ColumnName("d287"), LoadColumn(287)]
        public float D287 { get; set; }


        [ColumnName("d288"), LoadColumn(288)]
        public float D288 { get; set; }


        [ColumnName("d289"), LoadColumn(289)]
        public float D289 { get; set; }


        [ColumnName("d290"), LoadColumn(290)]
        public float D290 { get; set; }


        [ColumnName("d291"), LoadColumn(291)]
        public float D291 { get; set; }


        [ColumnName("d292"), LoadColumn(292)]
        public float D292 { get; set; }


        [ColumnName("d293"), LoadColumn(293)]
        public float D293 { get; set; }


        [ColumnName("d294"), LoadColumn(294)]
        public float D294 { get; set; }


        [ColumnName("d295"), LoadColumn(295)]
        public float D295 { get; set; }


        [ColumnName("d296"), LoadColumn(296)]
        public float D296 { get; set; }


        [ColumnName("d297"), LoadColumn(297)]
        public float D297 { get; set; }


        [ColumnName("d298"), LoadColumn(298)]
        public float D298 { get; set; }


        [ColumnName("d299"), LoadColumn(299)]
        public float D299 { get; set; }


        [ColumnName("d300"), LoadColumn(300)]
        public float D300 { get; set; }


        [ColumnName("d301"), LoadColumn(301)]
        public float D301 { get; set; }


        [ColumnName("d302"), LoadColumn(302)]
        public float D302 { get; set; }


        [ColumnName("d303"), LoadColumn(303)]
        public float D303 { get; set; }


        [ColumnName("d304"), LoadColumn(304)]
        public float D304 { get; set; }


        [ColumnName("d305"), LoadColumn(305)]
        public float D305 { get; set; }


        [ColumnName("d306"), LoadColumn(306)]
        public float D306 { get; set; }


        [ColumnName("d307"), LoadColumn(307)]
        public float D307 { get; set; }


        [ColumnName("d308"), LoadColumn(308)]
        public float D308 { get; set; }


        [ColumnName("d309"), LoadColumn(309)]
        public float D309 { get; set; }


        [ColumnName("d310"), LoadColumn(310)]
        public float D310 { get; set; }


        [ColumnName("d311"), LoadColumn(311)]
        public float D311 { get; set; }


        [ColumnName("d312"), LoadColumn(312)]
        public float D312 { get; set; }


        [ColumnName("d313"), LoadColumn(313)]
        public float D313 { get; set; }


        [ColumnName("d314"), LoadColumn(314)]
        public float D314 { get; set; }


        [ColumnName("d315"), LoadColumn(315)]
        public float D315 { get; set; }


        [ColumnName("d316"), LoadColumn(316)]
        public float D316 { get; set; }


        [ColumnName("d317"), LoadColumn(317)]
        public float D317 { get; set; }


        [ColumnName("d318"), LoadColumn(318)]
        public float D318 { get; set; }


        [ColumnName("d319"), LoadColumn(319)]
        public float D319 { get; set; }


        [ColumnName("d320"), LoadColumn(320)]
        public float D320 { get; set; }


        [ColumnName("d321"), LoadColumn(321)]
        public float D321 { get; set; }


        [ColumnName("d322"), LoadColumn(322)]
        public float D322 { get; set; }


        [ColumnName("d323"), LoadColumn(323)]
        public float D323 { get; set; }


        [ColumnName("d324"), LoadColumn(324)]
        public float D324 { get; set; }


        [ColumnName("d325"), LoadColumn(325)]
        public float D325 { get; set; }


        [ColumnName("d326"), LoadColumn(326)]
        public float D326 { get; set; }


        [ColumnName("d327"), LoadColumn(327)]
        public float D327 { get; set; }


        [ColumnName("d328"), LoadColumn(328)]
        public float D328 { get; set; }


        [ColumnName("d329"), LoadColumn(329)]
        public float D329 { get; set; }


        [ColumnName("d330"), LoadColumn(330)]
        public float D330 { get; set; }


        [ColumnName("d331"), LoadColumn(331)]
        public float D331 { get; set; }


        [ColumnName("d332"), LoadColumn(332)]
        public float D332 { get; set; }


        [ColumnName("d333"), LoadColumn(333)]
        public float D333 { get; set; }


        [ColumnName("d334"), LoadColumn(334)]
        public float D334 { get; set; }


        [ColumnName("d335"), LoadColumn(335)]
        public float D335 { get; set; }


        [ColumnName("d336"), LoadColumn(336)]
        public float D336 { get; set; }


        [ColumnName("d337"), LoadColumn(337)]
        public float D337 { get; set; }


        [ColumnName("d338"), LoadColumn(338)]
        public float D338 { get; set; }


        [ColumnName("d339"), LoadColumn(339)]
        public float D339 { get; set; }


        [ColumnName("d340"), LoadColumn(340)]
        public float D340 { get; set; }


        [ColumnName("d341"), LoadColumn(341)]
        public float D341 { get; set; }


        [ColumnName("d342"), LoadColumn(342)]
        public float D342 { get; set; }


        [ColumnName("d343"), LoadColumn(343)]
        public float D343 { get; set; }


        [ColumnName("d344"), LoadColumn(344)]
        public float D344 { get; set; }


        [ColumnName("d345"), LoadColumn(345)]
        public float D345 { get; set; }


        [ColumnName("d346"), LoadColumn(346)]
        public float D346 { get; set; }


        [ColumnName("d347"), LoadColumn(347)]
        public float D347 { get; set; }


        [ColumnName("d348"), LoadColumn(348)]
        public float D348 { get; set; }


        [ColumnName("d349"), LoadColumn(349)]
        public float D349 { get; set; }


        [ColumnName("d350"), LoadColumn(350)]
        public float D350 { get; set; }


        [ColumnName("d351"), LoadColumn(351)]
        public float D351 { get; set; }


        [ColumnName("d352"), LoadColumn(352)]
        public float D352 { get; set; }


        [ColumnName("d353"), LoadColumn(353)]
        public float D353 { get; set; }


        [ColumnName("d354"), LoadColumn(354)]
        public float D354 { get; set; }


        [ColumnName("d355"), LoadColumn(355)]
        public float D355 { get; set; }


        [ColumnName("d356"), LoadColumn(356)]
        public float D356 { get; set; }


        [ColumnName("d357"), LoadColumn(357)]
        public float D357 { get; set; }


        [ColumnName("d358"), LoadColumn(358)]
        public float D358 { get; set; }


        [ColumnName("d359"), LoadColumn(359)]
        public float D359 { get; set; }


        [ColumnName("d360"), LoadColumn(360)]
        public float D360 { get; set; }


        [ColumnName("d361"), LoadColumn(361)]
        public float D361 { get; set; }


        [ColumnName("d362"), LoadColumn(362)]
        public float D362 { get; set; }


        [ColumnName("d363"), LoadColumn(363)]
        public float D363 { get; set; }


        [ColumnName("d364"), LoadColumn(364)]
        public float D364 { get; set; }


        [ColumnName("d365"), LoadColumn(365)]
        public float D365 { get; set; }


        [ColumnName("d366"), LoadColumn(366)]
        public float D366 { get; set; }


        [ColumnName("d367"), LoadColumn(367)]
        public float D367 { get; set; }


        [ColumnName("d368"), LoadColumn(368)]
        public float D368 { get; set; }


        [ColumnName("d369"), LoadColumn(369)]
        public float D369 { get; set; }


        [ColumnName("d370"), LoadColumn(370)]
        public float D370 { get; set; }


        [ColumnName("d371"), LoadColumn(371)]
        public float D371 { get; set; }


        [ColumnName("d372"), LoadColumn(372)]
        public float D372 { get; set; }


        [ColumnName("d373"), LoadColumn(373)]
        public float D373 { get; set; }


        [ColumnName("d374"), LoadColumn(374)]
        public float D374 { get; set; }


        [ColumnName("d375"), LoadColumn(375)]
        public float D375 { get; set; }


        [ColumnName("d376"), LoadColumn(376)]
        public float D376 { get; set; }


        [ColumnName("d377"), LoadColumn(377)]
        public float D377 { get; set; }


        [ColumnName("d378"), LoadColumn(378)]
        public float D378 { get; set; }


        [ColumnName("d379"), LoadColumn(379)]
        public float D379 { get; set; }


        [ColumnName("d380"), LoadColumn(380)]
        public float D380 { get; set; }


        [ColumnName("d381"), LoadColumn(381)]
        public float D381 { get; set; }


        [ColumnName("d382"), LoadColumn(382)]
        public float D382 { get; set; }


        [ColumnName("d383"), LoadColumn(383)]
        public float D383 { get; set; }


        [ColumnName("d384"), LoadColumn(384)]
        public float D384 { get; set; }


        [ColumnName("d385"), LoadColumn(385)]
        public float D385 { get; set; }


        [ColumnName("d386"), LoadColumn(386)]
        public float D386 { get; set; }


        [ColumnName("d387"), LoadColumn(387)]
        public float D387 { get; set; }


        [ColumnName("d388"), LoadColumn(388)]
        public float D388 { get; set; }


        [ColumnName("d389"), LoadColumn(389)]
        public float D389 { get; set; }


        [ColumnName("d390"), LoadColumn(390)]
        public float D390 { get; set; }


        [ColumnName("d391"), LoadColumn(391)]
        public float D391 { get; set; }


        [ColumnName("d392"), LoadColumn(392)]
        public float D392 { get; set; }


        [ColumnName("d393"), LoadColumn(393)]
        public float D393 { get; set; }


        [ColumnName("d394"), LoadColumn(394)]
        public float D394 { get; set; }


        [ColumnName("d395"), LoadColumn(395)]
        public float D395 { get; set; }


        [ColumnName("d396"), LoadColumn(396)]
        public float D396 { get; set; }


        [ColumnName("d397"), LoadColumn(397)]
        public float D397 { get; set; }


        [ColumnName("d398"), LoadColumn(398)]
        public float D398 { get; set; }


        [ColumnName("d399"), LoadColumn(399)]
        public float D399 { get; set; }


        [ColumnName("d400"), LoadColumn(400)]
        public float D400 { get; set; }


        [ColumnName("d401"), LoadColumn(401)]
        public float D401 { get; set; }


        [ColumnName("d402"), LoadColumn(402)]
        public float D402 { get; set; }


        [ColumnName("d403"), LoadColumn(403)]
        public float D403 { get; set; }


        [ColumnName("d404"), LoadColumn(404)]
        public float D404 { get; set; }


        [ColumnName("d405"), LoadColumn(405)]
        public float D405 { get; set; }


        [ColumnName("d406"), LoadColumn(406)]
        public float D406 { get; set; }


        [ColumnName("d407"), LoadColumn(407)]
        public float D407 { get; set; }


        [ColumnName("d408"), LoadColumn(408)]
        public float D408 { get; set; }


        [ColumnName("d409"), LoadColumn(409)]
        public float D409 { get; set; }


        [ColumnName("d410"), LoadColumn(410)]
        public float D410 { get; set; }


        [ColumnName("d411"), LoadColumn(411)]
        public float D411 { get; set; }


        [ColumnName("d412"), LoadColumn(412)]
        public float D412 { get; set; }


        [ColumnName("d413"), LoadColumn(413)]
        public float D413 { get; set; }


        [ColumnName("d414"), LoadColumn(414)]
        public float D414 { get; set; }


        [ColumnName("d415"), LoadColumn(415)]
        public float D415 { get; set; }


        [ColumnName("d416"), LoadColumn(416)]
        public float D416 { get; set; }


        [ColumnName("d417"), LoadColumn(417)]
        public float D417 { get; set; }


        [ColumnName("d418"), LoadColumn(418)]
        public float D418 { get; set; }


        [ColumnName("d419"), LoadColumn(419)]
        public float D419 { get; set; }


        [ColumnName("d420"), LoadColumn(420)]
        public float D420 { get; set; }


        [ColumnName("d421"), LoadColumn(421)]
        public float D421 { get; set; }


        [ColumnName("d422"), LoadColumn(422)]
        public float D422 { get; set; }


        [ColumnName("d423"), LoadColumn(423)]
        public float D423 { get; set; }


        [ColumnName("d424"), LoadColumn(424)]
        public float D424 { get; set; }


        [ColumnName("d425"), LoadColumn(425)]
        public float D425 { get; set; }


        [ColumnName("d426"), LoadColumn(426)]
        public float D426 { get; set; }


        [ColumnName("d427"), LoadColumn(427)]
        public float D427 { get; set; }


        [ColumnName("d428"), LoadColumn(428)]
        public float D428 { get; set; }


        [ColumnName("d429"), LoadColumn(429)]
        public float D429 { get; set; }


        [ColumnName("d430"), LoadColumn(430)]
        public float D430 { get; set; }


        [ColumnName("d431"), LoadColumn(431)]
        public float D431 { get; set; }


        [ColumnName("d432"), LoadColumn(432)]
        public float D432 { get; set; }


        [ColumnName("d433"), LoadColumn(433)]
        public float D433 { get; set; }


        [ColumnName("d434"), LoadColumn(434)]
        public float D434 { get; set; }


        [ColumnName("d435"), LoadColumn(435)]
        public float D435 { get; set; }


        [ColumnName("d436"), LoadColumn(436)]
        public float D436 { get; set; }


        [ColumnName("d437"), LoadColumn(437)]
        public float D437 { get; set; }


        [ColumnName("d438"), LoadColumn(438)]
        public float D438 { get; set; }


        [ColumnName("d439"), LoadColumn(439)]
        public float D439 { get; set; }


        [ColumnName("d440"), LoadColumn(440)]
        public float D440 { get; set; }


        [ColumnName("d441"), LoadColumn(441)]
        public float D441 { get; set; }


        [ColumnName("d442"), LoadColumn(442)]
        public float D442 { get; set; }


        [ColumnName("d443"), LoadColumn(443)]
        public float D443 { get; set; }


        [ColumnName("d444"), LoadColumn(444)]
        public float D444 { get; set; }


        [ColumnName("d445"), LoadColumn(445)]
        public float D445 { get; set; }


        [ColumnName("d446"), LoadColumn(446)]
        public float D446 { get; set; }


        [ColumnName("d447"), LoadColumn(447)]
        public float D447 { get; set; }


        [ColumnName("d448"), LoadColumn(448)]
        public float D448 { get; set; }


        [ColumnName("d449"), LoadColumn(449)]
        public float D449 { get; set; }


        [ColumnName("d450"), LoadColumn(450)]
        public float D450 { get; set; }


        [ColumnName("d451"), LoadColumn(451)]
        public float D451 { get; set; }


        [ColumnName("d452"), LoadColumn(452)]
        public float D452 { get; set; }


        [ColumnName("d453"), LoadColumn(453)]
        public float D453 { get; set; }


        [ColumnName("d454"), LoadColumn(454)]
        public float D454 { get; set; }


        [ColumnName("d455"), LoadColumn(455)]
        public float D455 { get; set; }


        [ColumnName("d456"), LoadColumn(456)]
        public float D456 { get; set; }


        [ColumnName("d457"), LoadColumn(457)]
        public float D457 { get; set; }


        [ColumnName("d458"), LoadColumn(458)]
        public float D458 { get; set; }


        [ColumnName("d459"), LoadColumn(459)]
        public float D459 { get; set; }


        [ColumnName("d460"), LoadColumn(460)]
        public float D460 { get; set; }


        [ColumnName("d461"), LoadColumn(461)]
        public float D461 { get; set; }


        [ColumnName("d462"), LoadColumn(462)]
        public float D462 { get; set; }


        [ColumnName("d463"), LoadColumn(463)]
        public float D463 { get; set; }


        [ColumnName("d464"), LoadColumn(464)]
        public float D464 { get; set; }


        [ColumnName("d465"), LoadColumn(465)]
        public float D465 { get; set; }


        [ColumnName("d466"), LoadColumn(466)]
        public float D466 { get; set; }


        [ColumnName("d467"), LoadColumn(467)]
        public float D467 { get; set; }


        [ColumnName("d468"), LoadColumn(468)]
        public float D468 { get; set; }


        [ColumnName("d469"), LoadColumn(469)]
        public float D469 { get; set; }


        [ColumnName("d470"), LoadColumn(470)]
        public float D470 { get; set; }


        [ColumnName("d471"), LoadColumn(471)]
        public float D471 { get; set; }


        [ColumnName("d472"), LoadColumn(472)]
        public float D472 { get; set; }


        [ColumnName("d473"), LoadColumn(473)]
        public float D473 { get; set; }


        [ColumnName("d474"), LoadColumn(474)]
        public float D474 { get; set; }


        [ColumnName("d475"), LoadColumn(475)]
        public float D475 { get; set; }


        [ColumnName("d476"), LoadColumn(476)]
        public float D476 { get; set; }


        [ColumnName("d477"), LoadColumn(477)]
        public float D477 { get; set; }


        [ColumnName("d478"), LoadColumn(478)]
        public float D478 { get; set; }


        [ColumnName("d479"), LoadColumn(479)]
        public float D479 { get; set; }


        [ColumnName("d480"), LoadColumn(480)]
        public float D480 { get; set; }


        [ColumnName("d481"), LoadColumn(481)]
        public float D481 { get; set; }


        [ColumnName("d482"), LoadColumn(482)]
        public float D482 { get; set; }


        [ColumnName("d483"), LoadColumn(483)]
        public float D483 { get; set; }


        [ColumnName("d484"), LoadColumn(484)]
        public float D484 { get; set; }


        [ColumnName("d485"), LoadColumn(485)]
        public float D485 { get; set; }


        [ColumnName("d486"), LoadColumn(486)]
        public float D486 { get; set; }


        [ColumnName("d487"), LoadColumn(487)]
        public float D487 { get; set; }


        [ColumnName("d488"), LoadColumn(488)]
        public float D488 { get; set; }


        [ColumnName("d489"), LoadColumn(489)]
        public float D489 { get; set; }


        [ColumnName("d490"), LoadColumn(490)]
        public float D490 { get; set; }


        [ColumnName("d491"), LoadColumn(491)]
        public float D491 { get; set; }


        [ColumnName("d492"), LoadColumn(492)]
        public float D492 { get; set; }


        [ColumnName("d493"), LoadColumn(493)]
        public float D493 { get; set; }


        [ColumnName("d494"), LoadColumn(494)]
        public float D494 { get; set; }


        [ColumnName("d495"), LoadColumn(495)]
        public float D495 { get; set; }


        [ColumnName("d496"), LoadColumn(496)]
        public float D496 { get; set; }


        [ColumnName("d497"), LoadColumn(497)]
        public float D497 { get; set; }


        [ColumnName("d498"), LoadColumn(498)]
        public float D498 { get; set; }


        [ColumnName("d499"), LoadColumn(499)]
        public float D499 { get; set; }


        [ColumnName("d500"), LoadColumn(500)]
        public float D500 { get; set; }


        [ColumnName("d501"), LoadColumn(501)]
        public float D501 { get; set; }


        [ColumnName("d502"), LoadColumn(502)]
        public float D502 { get; set; }


        [ColumnName("d503"), LoadColumn(503)]
        public float D503 { get; set; }


        [ColumnName("d504"), LoadColumn(504)]
        public float D504 { get; set; }


        [ColumnName("d505"), LoadColumn(505)]
        public float D505 { get; set; }


        [ColumnName("d506"), LoadColumn(506)]
        public float D506 { get; set; }


        [ColumnName("d507"), LoadColumn(507)]
        public float D507 { get; set; }


        [ColumnName("d508"), LoadColumn(508)]
        public float D508 { get; set; }


        [ColumnName("d509"), LoadColumn(509)]
        public float D509 { get; set; }


        [ColumnName("d510"), LoadColumn(510)]
        public float D510 { get; set; }


        [ColumnName("d511"), LoadColumn(511)]
        public float D511 { get; set; }


        [ColumnName("d512"), LoadColumn(512)]
        public float D512 { get; set; }


        [ColumnName("d513"), LoadColumn(513)]
        public float D513 { get; set; }


        [ColumnName("d514"), LoadColumn(514)]
        public float D514 { get; set; }


        [ColumnName("d515"), LoadColumn(515)]
        public float D515 { get; set; }


        [ColumnName("d516"), LoadColumn(516)]
        public float D516 { get; set; }


        [ColumnName("d517"), LoadColumn(517)]
        public float D517 { get; set; }


        [ColumnName("d518"), LoadColumn(518)]
        public float D518 { get; set; }


        [ColumnName("d519"), LoadColumn(519)]
        public float D519 { get; set; }


        [ColumnName("d520"), LoadColumn(520)]
        public float D520 { get; set; }


        [ColumnName("d521"), LoadColumn(521)]
        public float D521 { get; set; }


        [ColumnName("d522"), LoadColumn(522)]
        public float D522 { get; set; }


        [ColumnName("d523"), LoadColumn(523)]
        public float D523 { get; set; }


        [ColumnName("d524"), LoadColumn(524)]
        public float D524 { get; set; }


        [ColumnName("d525"), LoadColumn(525)]
        public float D525 { get; set; }


        [ColumnName("d526"), LoadColumn(526)]
        public float D526 { get; set; }


        [ColumnName("d527"), LoadColumn(527)]
        public float D527 { get; set; }


        [ColumnName("d528"), LoadColumn(528)]
        public float D528 { get; set; }


        [ColumnName("d529"), LoadColumn(529)]
        public float D529 { get; set; }


        [ColumnName("d530"), LoadColumn(530)]
        public float D530 { get; set; }


        [ColumnName("d531"), LoadColumn(531)]
        public float D531 { get; set; }


        [ColumnName("d532"), LoadColumn(532)]
        public float D532 { get; set; }


        [ColumnName("d533"), LoadColumn(533)]
        public float D533 { get; set; }


        [ColumnName("d534"), LoadColumn(534)]
        public float D534 { get; set; }


        [ColumnName("d535"), LoadColumn(535)]
        public float D535 { get; set; }


        [ColumnName("d536"), LoadColumn(536)]
        public float D536 { get; set; }


        [ColumnName("d537"), LoadColumn(537)]
        public float D537 { get; set; }


        [ColumnName("d538"), LoadColumn(538)]
        public float D538 { get; set; }


        [ColumnName("d539"), LoadColumn(539)]
        public float D539 { get; set; }


        [ColumnName("d540"), LoadColumn(540)]
        public float D540 { get; set; }


        [ColumnName("d541"), LoadColumn(541)]
        public float D541 { get; set; }


        [ColumnName("d542"), LoadColumn(542)]
        public float D542 { get; set; }


        [ColumnName("d543"), LoadColumn(543)]
        public float D543 { get; set; }


        [ColumnName("d544"), LoadColumn(544)]
        public float D544 { get; set; }


        [ColumnName("d545"), LoadColumn(545)]
        public float D545 { get; set; }


        [ColumnName("d546"), LoadColumn(546)]
        public float D546 { get; set; }


        [ColumnName("d547"), LoadColumn(547)]
        public float D547 { get; set; }


        [ColumnName("d548"), LoadColumn(548)]
        public float D548 { get; set; }


        [ColumnName("d549"), LoadColumn(549)]
        public float D549 { get; set; }


        [ColumnName("d550"), LoadColumn(550)]
        public float D550 { get; set; }


        [ColumnName("d551"), LoadColumn(551)]
        public float D551 { get; set; }


        [ColumnName("d552"), LoadColumn(552)]
        public float D552 { get; set; }


        [ColumnName("d553"), LoadColumn(553)]
        public float D553 { get; set; }


        [ColumnName("d554"), LoadColumn(554)]
        public float D554 { get; set; }


        [ColumnName("d555"), LoadColumn(555)]
        public float D555 { get; set; }


        [ColumnName("d556"), LoadColumn(556)]
        public float D556 { get; set; }


        [ColumnName("d557"), LoadColumn(557)]
        public float D557 { get; set; }


        [ColumnName("d558"), LoadColumn(558)]
        public float D558 { get; set; }


        [ColumnName("d559"), LoadColumn(559)]
        public float D559 { get; set; }


        [ColumnName("d560"), LoadColumn(560)]
        public float D560 { get; set; }


        [ColumnName("d561"), LoadColumn(561)]
        public float D561 { get; set; }


        [ColumnName("d562"), LoadColumn(562)]
        public float D562 { get; set; }


        [ColumnName("d563"), LoadColumn(563)]
        public float D563 { get; set; }


        [ColumnName("d564"), LoadColumn(564)]
        public float D564 { get; set; }


        [ColumnName("d565"), LoadColumn(565)]
        public float D565 { get; set; }


        [ColumnName("d566"), LoadColumn(566)]
        public float D566 { get; set; }


        [ColumnName("d567"), LoadColumn(567)]
        public float D567 { get; set; }


        [ColumnName("d568"), LoadColumn(568)]
        public float D568 { get; set; }


        [ColumnName("d569"), LoadColumn(569)]
        public float D569 { get; set; }


        [ColumnName("d570"), LoadColumn(570)]
        public float D570 { get; set; }


        [ColumnName("d571"), LoadColumn(571)]
        public float D571 { get; set; }


        [ColumnName("d572"), LoadColumn(572)]
        public float D572 { get; set; }


        [ColumnName("d573"), LoadColumn(573)]
        public float D573 { get; set; }


        [ColumnName("d574"), LoadColumn(574)]
        public float D574 { get; set; }


        [ColumnName("d575"), LoadColumn(575)]
        public float D575 { get; set; }


        [ColumnName("d576"), LoadColumn(576)]
        public float D576 { get; set; }


        [ColumnName("d577"), LoadColumn(577)]
        public float D577 { get; set; }


        [ColumnName("d578"), LoadColumn(578)]
        public float D578 { get; set; }


        [ColumnName("d579"), LoadColumn(579)]
        public float D579 { get; set; }


        [ColumnName("d580"), LoadColumn(580)]
        public float D580 { get; set; }


        [ColumnName("d581"), LoadColumn(581)]
        public float D581 { get; set; }


        [ColumnName("d582"), LoadColumn(582)]
        public float D582 { get; set; }


        [ColumnName("d583"), LoadColumn(583)]
        public float D583 { get; set; }


        [ColumnName("d584"), LoadColumn(584)]
        public float D584 { get; set; }


        [ColumnName("d585"), LoadColumn(585)]
        public float D585 { get; set; }


        [ColumnName("d586"), LoadColumn(586)]
        public float D586 { get; set; }


        [ColumnName("d587"), LoadColumn(587)]
        public float D587 { get; set; }


        [ColumnName("d588"), LoadColumn(588)]
        public float D588 { get; set; }


        [ColumnName("d589"), LoadColumn(589)]
        public float D589 { get; set; }


        [ColumnName("d590"), LoadColumn(590)]
        public float D590 { get; set; }


        [ColumnName("d591"), LoadColumn(591)]
        public float D591 { get; set; }


        [ColumnName("d592"), LoadColumn(592)]
        public float D592 { get; set; }


        [ColumnName("d593"), LoadColumn(593)]
        public float D593 { get; set; }


        [ColumnName("d594"), LoadColumn(594)]
        public float D594 { get; set; }


        [ColumnName("d595"), LoadColumn(595)]
        public float D595 { get; set; }


        [ColumnName("d596"), LoadColumn(596)]
        public float D596 { get; set; }


        [ColumnName("d597"), LoadColumn(597)]
        public float D597 { get; set; }


        [ColumnName("d598"), LoadColumn(598)]
        public float D598 { get; set; }


        [ColumnName("d599"), LoadColumn(599)]
        public float D599 { get; set; }


        [ColumnName("d600"), LoadColumn(600)]
        public float D600 { get; set; }


        [ColumnName("d601"), LoadColumn(601)]
        public float D601 { get; set; }


        [ColumnName("d602"), LoadColumn(602)]
        public float D602 { get; set; }


        [ColumnName("d603"), LoadColumn(603)]
        public float D603 { get; set; }


        [ColumnName("d604"), LoadColumn(604)]
        public float D604 { get; set; }


        [ColumnName("d605"), LoadColumn(605)]
        public float D605 { get; set; }


        [ColumnName("d606"), LoadColumn(606)]
        public float D606 { get; set; }


        [ColumnName("d607"), LoadColumn(607)]
        public float D607 { get; set; }


        [ColumnName("d608"), LoadColumn(608)]
        public float D608 { get; set; }


        [ColumnName("d609"), LoadColumn(609)]
        public float D609 { get; set; }


        [ColumnName("d610"), LoadColumn(610)]
        public float D610 { get; set; }


        [ColumnName("d611"), LoadColumn(611)]
        public float D611 { get; set; }


        [ColumnName("d612"), LoadColumn(612)]
        public float D612 { get; set; }


        [ColumnName("d613"), LoadColumn(613)]
        public float D613 { get; set; }


        [ColumnName("d614"), LoadColumn(614)]
        public float D614 { get; set; }


        [ColumnName("d615"), LoadColumn(615)]
        public float D615 { get; set; }


        [ColumnName("d616"), LoadColumn(616)]
        public float D616 { get; set; }


        [ColumnName("d617"), LoadColumn(617)]
        public float D617 { get; set; }


        [ColumnName("d618"), LoadColumn(618)]
        public float D618 { get; set; }


        [ColumnName("d619"), LoadColumn(619)]
        public float D619 { get; set; }


        [ColumnName("d620"), LoadColumn(620)]
        public float D620 { get; set; }


        [ColumnName("d621"), LoadColumn(621)]
        public float D621 { get; set; }


        [ColumnName("d622"), LoadColumn(622)]
        public float D622 { get; set; }


        [ColumnName("d623"), LoadColumn(623)]
        public float D623 { get; set; }


        [ColumnName("d624"), LoadColumn(624)]
        public float D624 { get; set; }


        [ColumnName("d625"), LoadColumn(625)]
        public float D625 { get; set; }


        [ColumnName("d626"), LoadColumn(626)]
        public float D626 { get; set; }


        [ColumnName("d627"), LoadColumn(627)]
        public float D627 { get; set; }


        [ColumnName("d628"), LoadColumn(628)]
        public float D628 { get; set; }


        [ColumnName("d629"), LoadColumn(629)]
        public float D629 { get; set; }


        [ColumnName("d630"), LoadColumn(630)]
        public float D630 { get; set; }


        [ColumnName("d631"), LoadColumn(631)]
        public float D631 { get; set; }


        [ColumnName("d632"), LoadColumn(632)]
        public float D632 { get; set; }


        [ColumnName("d633"), LoadColumn(633)]
        public float D633 { get; set; }


        [ColumnName("d634"), LoadColumn(634)]
        public float D634 { get; set; }


        [ColumnName("d635"), LoadColumn(635)]
        public float D635 { get; set; }


        [ColumnName("d636"), LoadColumn(636)]
        public float D636 { get; set; }


        [ColumnName("d637"), LoadColumn(637)]
        public float D637 { get; set; }


        [ColumnName("d638"), LoadColumn(638)]
        public float D638 { get; set; }


        [ColumnName("d639"), LoadColumn(639)]
        public float D639 { get; set; }


        [ColumnName("d640"), LoadColumn(640)]
        public float D640 { get; set; }


        [ColumnName("d641"), LoadColumn(641)]
        public float D641 { get; set; }


        [ColumnName("d642"), LoadColumn(642)]
        public float D642 { get; set; }


        [ColumnName("d643"), LoadColumn(643)]
        public float D643 { get; set; }


        [ColumnName("d644"), LoadColumn(644)]
        public float D644 { get; set; }


        [ColumnName("d645"), LoadColumn(645)]
        public float D645 { get; set; }


        [ColumnName("d646"), LoadColumn(646)]
        public float D646 { get; set; }


        [ColumnName("d647"), LoadColumn(647)]
        public float D647 { get; set; }


        [ColumnName("d648"), LoadColumn(648)]
        public float D648 { get; set; }


        [ColumnName("d649"), LoadColumn(649)]
        public float D649 { get; set; }


        [ColumnName("d650"), LoadColumn(650)]
        public float D650 { get; set; }


        [ColumnName("d651"), LoadColumn(651)]
        public float D651 { get; set; }


        [ColumnName("d652"), LoadColumn(652)]
        public float D652 { get; set; }


        [ColumnName("d653"), LoadColumn(653)]
        public float D653 { get; set; }


        [ColumnName("d654"), LoadColumn(654)]
        public float D654 { get; set; }


        [ColumnName("d655"), LoadColumn(655)]
        public float D655 { get; set; }


        [ColumnName("d656"), LoadColumn(656)]
        public float D656 { get; set; }


        [ColumnName("d657"), LoadColumn(657)]
        public float D657 { get; set; }


        [ColumnName("d658"), LoadColumn(658)]
        public float D658 { get; set; }


        [ColumnName("d659"), LoadColumn(659)]
        public float D659 { get; set; }


        [ColumnName("d660"), LoadColumn(660)]
        public float D660 { get; set; }


        [ColumnName("d661"), LoadColumn(661)]
        public float D661 { get; set; }


        [ColumnName("d662"), LoadColumn(662)]
        public float D662 { get; set; }


        [ColumnName("d663"), LoadColumn(663)]
        public float D663 { get; set; }


        [ColumnName("d664"), LoadColumn(664)]
        public float D664 { get; set; }


        [ColumnName("d665"), LoadColumn(665)]
        public float D665 { get; set; }


        [ColumnName("d666"), LoadColumn(666)]
        public float D666 { get; set; }


        [ColumnName("d667"), LoadColumn(667)]
        public float D667 { get; set; }


        [ColumnName("d668"), LoadColumn(668)]
        public float D668 { get; set; }


        [ColumnName("d669"), LoadColumn(669)]
        public float D669 { get; set; }


        [ColumnName("d670"), LoadColumn(670)]
        public float D670 { get; set; }


        [ColumnName("d671"), LoadColumn(671)]
        public float D671 { get; set; }


        [ColumnName("d672"), LoadColumn(672)]
        public float D672 { get; set; }


        [ColumnName("d673"), LoadColumn(673)]
        public float D673 { get; set; }


        [ColumnName("d674"), LoadColumn(674)]
        public float D674 { get; set; }


        [ColumnName("d675"), LoadColumn(675)]
        public float D675 { get; set; }


        [ColumnName("d676"), LoadColumn(676)]
        public float D676 { get; set; }


        [ColumnName("d677"), LoadColumn(677)]
        public float D677 { get; set; }


        [ColumnName("d678"), LoadColumn(678)]
        public float D678 { get; set; }


        [ColumnName("d679"), LoadColumn(679)]
        public float D679 { get; set; }


        [ColumnName("d680"), LoadColumn(680)]
        public float D680 { get; set; }


        [ColumnName("d681"), LoadColumn(681)]
        public float D681 { get; set; }


        [ColumnName("d682"), LoadColumn(682)]
        public float D682 { get; set; }


        [ColumnName("d683"), LoadColumn(683)]
        public float D683 { get; set; }


        [ColumnName("d684"), LoadColumn(684)]
        public float D684 { get; set; }


        [ColumnName("d685"), LoadColumn(685)]
        public float D685 { get; set; }


        [ColumnName("d686"), LoadColumn(686)]
        public float D686 { get; set; }


        [ColumnName("d687"), LoadColumn(687)]
        public float D687 { get; set; }


        [ColumnName("d688"), LoadColumn(688)]
        public float D688 { get; set; }


        [ColumnName("d689"), LoadColumn(689)]
        public float D689 { get; set; }


        [ColumnName("d690"), LoadColumn(690)]
        public float D690 { get; set; }


        [ColumnName("d691"), LoadColumn(691)]
        public float D691 { get; set; }


        [ColumnName("d692"), LoadColumn(692)]
        public float D692 { get; set; }


        [ColumnName("d693"), LoadColumn(693)]
        public float D693 { get; set; }


        [ColumnName("d694"), LoadColumn(694)]
        public float D694 { get; set; }


        [ColumnName("d695"), LoadColumn(695)]
        public float D695 { get; set; }


        [ColumnName("d696"), LoadColumn(696)]
        public float D696 { get; set; }


        [ColumnName("d697"), LoadColumn(697)]
        public float D697 { get; set; }


        [ColumnName("d698"), LoadColumn(698)]
        public float D698 { get; set; }


        [ColumnName("d699"), LoadColumn(699)]
        public float D699 { get; set; }


        [ColumnName("d700"), LoadColumn(700)]
        public float D700 { get; set; }


        [ColumnName("d701"), LoadColumn(701)]
        public float D701 { get; set; }


        [ColumnName("d702"), LoadColumn(702)]
        public float D702 { get; set; }


        [ColumnName("d703"), LoadColumn(703)]
        public float D703 { get; set; }


        [ColumnName("d704"), LoadColumn(704)]
        public float D704 { get; set; }


        [ColumnName("d705"), LoadColumn(705)]
        public float D705 { get; set; }


        [ColumnName("d706"), LoadColumn(706)]
        public float D706 { get; set; }


        [ColumnName("d707"), LoadColumn(707)]
        public float D707 { get; set; }


        [ColumnName("d708"), LoadColumn(708)]
        public float D708 { get; set; }


        [ColumnName("d709"), LoadColumn(709)]
        public float D709 { get; set; }


        [ColumnName("d710"), LoadColumn(710)]
        public float D710 { get; set; }


        [ColumnName("d711"), LoadColumn(711)]
        public float D711 { get; set; }


        [ColumnName("d712"), LoadColumn(712)]
        public float D712 { get; set; }


        [ColumnName("d713"), LoadColumn(713)]
        public float D713 { get; set; }


        [ColumnName("d714"), LoadColumn(714)]
        public float D714 { get; set; }


        [ColumnName("d715"), LoadColumn(715)]
        public float D715 { get; set; }


        [ColumnName("d716"), LoadColumn(716)]
        public float D716 { get; set; }


        [ColumnName("d717"), LoadColumn(717)]
        public float D717 { get; set; }


        [ColumnName("d718"), LoadColumn(718)]
        public float D718 { get; set; }


        [ColumnName("d719"), LoadColumn(719)]
        public float D719 { get; set; }


        [ColumnName("d720"), LoadColumn(720)]
        public float D720 { get; set; }


        [ColumnName("d721"), LoadColumn(721)]
        public float D721 { get; set; }


        [ColumnName("d722"), LoadColumn(722)]
        public float D722 { get; set; }


        [ColumnName("d723"), LoadColumn(723)]
        public float D723 { get; set; }


        [ColumnName("d724"), LoadColumn(724)]
        public float D724 { get; set; }


        [ColumnName("d725"), LoadColumn(725)]
        public float D725 { get; set; }


        [ColumnName("d726"), LoadColumn(726)]
        public float D726 { get; set; }


        [ColumnName("d727"), LoadColumn(727)]
        public float D727 { get; set; }


        [ColumnName("d728"), LoadColumn(728)]
        public float D728 { get; set; }


        [ColumnName("d729"), LoadColumn(729)]
        public float D729 { get; set; }


        [ColumnName("d730"), LoadColumn(730)]
        public float D730 { get; set; }


        [ColumnName("d731"), LoadColumn(731)]
        public float D731 { get; set; }


        [ColumnName("d732"), LoadColumn(732)]
        public float D732 { get; set; }


        [ColumnName("d733"), LoadColumn(733)]
        public float D733 { get; set; }


        [ColumnName("d734"), LoadColumn(734)]
        public float D734 { get; set; }


        [ColumnName("d735"), LoadColumn(735)]
        public float D735 { get; set; }


        [ColumnName("d736"), LoadColumn(736)]
        public float D736 { get; set; }


        [ColumnName("d737"), LoadColumn(737)]
        public float D737 { get; set; }


        [ColumnName("d738"), LoadColumn(738)]
        public float D738 { get; set; }


        [ColumnName("d739"), LoadColumn(739)]
        public float D739 { get; set; }


        [ColumnName("d740"), LoadColumn(740)]
        public float D740 { get; set; }


        [ColumnName("d741"), LoadColumn(741)]
        public float D741 { get; set; }


        [ColumnName("d742"), LoadColumn(742)]
        public float D742 { get; set; }


        [ColumnName("d743"), LoadColumn(743)]
        public float D743 { get; set; }


        [ColumnName("d744"), LoadColumn(744)]
        public float D744 { get; set; }


        [ColumnName("d745"), LoadColumn(745)]
        public float D745 { get; set; }


        [ColumnName("d746"), LoadColumn(746)]
        public float D746 { get; set; }


        [ColumnName("d747"), LoadColumn(747)]
        public float D747 { get; set; }


        [ColumnName("d748"), LoadColumn(748)]
        public float D748 { get; set; }


        [ColumnName("d749"), LoadColumn(749)]
        public float D749 { get; set; }


        [ColumnName("d750"), LoadColumn(750)]
        public float D750 { get; set; }


        [ColumnName("d751"), LoadColumn(751)]
        public float D751 { get; set; }


        [ColumnName("d752"), LoadColumn(752)]
        public float D752 { get; set; }


        [ColumnName("d753"), LoadColumn(753)]
        public float D753 { get; set; }


        [ColumnName("d754"), LoadColumn(754)]
        public float D754 { get; set; }


        [ColumnName("d755"), LoadColumn(755)]
        public float D755 { get; set; }


        [ColumnName("d756"), LoadColumn(756)]
        public float D756 { get; set; }


        [ColumnName("d757"), LoadColumn(757)]
        public float D757 { get; set; }


        [ColumnName("d758"), LoadColumn(758)]
        public float D758 { get; set; }


        [ColumnName("d759"), LoadColumn(759)]
        public float D759 { get; set; }


        [ColumnName("d760"), LoadColumn(760)]
        public float D760 { get; set; }


        [ColumnName("d761"), LoadColumn(761)]
        public float D761 { get; set; }


        [ColumnName("d762"), LoadColumn(762)]
        public float D762 { get; set; }


        [ColumnName("d763"), LoadColumn(763)]
        public float D763 { get; set; }


        [ColumnName("d764"), LoadColumn(764)]
        public float D764 { get; set; }


        [ColumnName("d765"), LoadColumn(765)]
        public float D765 { get; set; }


        [ColumnName("d766"), LoadColumn(766)]
        public float D766 { get; set; }


        [ColumnName("d767"), LoadColumn(767)]
        public float D767 { get; set; }


        [ColumnName("d768"), LoadColumn(768)]
        public float D768 { get; set; }


        [ColumnName("d769"), LoadColumn(769)]
        public float D769 { get; set; }


        [ColumnName("d770"), LoadColumn(770)]
        public float D770 { get; set; }


        [ColumnName("d771"), LoadColumn(771)]
        public float D771 { get; set; }


        [ColumnName("d772"), LoadColumn(772)]
        public float D772 { get; set; }


        [ColumnName("d773"), LoadColumn(773)]
        public float D773 { get; set; }


        [ColumnName("d774"), LoadColumn(774)]
        public float D774 { get; set; }


        [ColumnName("d775"), LoadColumn(775)]
        public float D775 { get; set; }


        [ColumnName("d776"), LoadColumn(776)]
        public float D776 { get; set; }


        [ColumnName("d777"), LoadColumn(777)]
        public float D777 { get; set; }


        [ColumnName("d778"), LoadColumn(778)]
        public float D778 { get; set; }


        [ColumnName("d779"), LoadColumn(779)]
        public float D779 { get; set; }


        [ColumnName("d780"), LoadColumn(780)]
        public float D780 { get; set; }


        [ColumnName("d781"), LoadColumn(781)]
        public float D781 { get; set; }


        [ColumnName("d782"), LoadColumn(782)]
        public float D782 { get; set; }


        [ColumnName("d783"), LoadColumn(783)]
        public float D783 { get; set; }


        [ColumnName("d784"), LoadColumn(784)]
        public float D784 { get; set; }


    }
}
